---
title: "Kinsey Matthews"
subtitle: "PhD Student | Bren School of Environmental Science & Management, UC Santa Barbara"
---

## About Me

Kinsey Matthews (she/her) is a PhD student at the Bren School of Environmental Science and Management at UC Santa Barbara. She is co-advised by [Chris Free](https://marine.ucsb.edu/) and [Steve Gaines](https://bren.ucsb.edu/). Her research focuses on the relationships among marine species distributions, changing oceanographic conditions, and human uses of the ocean. She is especially interested in how adaptive and dynamic ocean management can be used to alleviate potential conflicts, such as those arising from fisheries bycatch or protected spaces.

Prior to Bren, she obtained her master's degree from Moss Landing Marine Laboratories (MLML), where her research aimed to better understand the efficacy of small-scale species distribution models of continental shelf fishes off California. After MLML, she was a California Sea Grant State Fellow with the California Fish and Game Commission, where she gained a deeper understanding of the science-policy interface and the regulatory process.

During her free time, Kinsey can be found backpacking in the Ventana Wilderness, freediving in the kelp forests, and reading fantasy books.

---

**PhD Student**
Bren School of Environmental Science & Management
University of California, Santa Barbara
📧 [kinseymatthews@ucsb.edu](mailto:kinseymatthews@ucsb.edu)
